#Note:
#1.variable explain

#TOPDIR         variable must be define,this indicates the top directory

#follow variable only defind one or didn't defined(for example,nor source directory)

#TARGETV         variable indicates build a executed file that name is variable value
#LIB            variable indicates build a lib file that name is variable value
#SHAREDLIBV     variable indicates build a shared lib file that name is variable value
#BUILDOBJ       variable indicates build a object file. the value can be anything but didn't empty

#exclude_dirs   variable indicates this directory didn't need build,for example 'include' or 'build'
#project_dirs   variable indicates which directory is project directory
#AutoNeedAppLib	add the library that can auto AR when this lib modify 
exclude_dirs= rtp
LIB = libnetwork.a

include $(MAKEFILELIB)


